const countryList = [
  { country: "Argentina", id: "ar", flag: "🇦🇷" },
  { country: "Australia", id: "au", flag: "🇦🇺" },
  { country: "Austria", id: "at", flag: "🇦🇹" },
  { country: "Belgium", id: "be", flag: "🇧🇪" },
  { country: "Brazil", id: "br", flag: "🇧🇷" },
  { country: "Bulgaria", id: "bg", flag: "🇧🇬" },
  { country: "Canada", id: "ca", flag: "🇨🇦" },
  { country: "China", id: "cn", flag: "🇨🇳" },
  { country: "Colombia", id: "co", flag: "🇨🇴" },
  { country: "Czech Republic", id: "cz", flag: "🇨🇿" },
  { country: "Egypt", id: "eg", flag: "🇪🇬" },
  { country: "France", id: "fr", flag: "🇫🇷" },
  { country: "Germany", id: "de", flag: "🇩🇪" },
  { country: "Greece", id: "gr", flag: "🇬🇷" },
  { country: "Hong Kong", id: "hk", flag: "🇭🇰" },
  { country: "Hungary", id: "hu", flag: "🇭🇺" },
  { country: "India", id: "in", flag: "🇮🇳" },
  { country: "Indonesia", id: "id", flag: "🇮🇩" },
  { country: "Ireland", id: "ie", flag: "🇮🇪" },
  { country: "Israel", id: "il", flag: "🇮🇱" },
  { country: "Italy", id: "it", flag: "🇮🇹" },
  { country: "Japan", id: "jp", flag: "🇯🇵" },
  { country: "Latvia", id: "lv", flag: "🇱🇻" },
  { country: "Lithuania", id: "lt", flag: "🇱🇹" },
  { country: "Malaysia", id: "my", flag: "🇲🇾" },
  { country: "Mexico", id: "mx", flag: "🇲🇽" },
  { country: "Morocco", id: "ma", flag: "🇲🇦" },
  { country: "Netherlands", id: "nl", flag: "🇳🇱" },
  { country: "New Zealand", id: "nz", flag: "🇳🇿" },
  { country: "Nigeria", id: "ng", flag: "🇳🇬" },
  { country: "Norway", id: "no", flag: "🇳🇴" },
  { country: "Philippines", id: "ph", flag: "🇵🇭" },
  { country: "Poland", id: "pl", flag: "🇵🇱" },
  { country: "Portugal", id: "pt", flag: "🇵🇹" },
  { country: "Romania", id: "ro", flag: "🇷🇴" },
  { country: "Russia", id: "ru", flag: "🇷🇺" },
  { country: "Saudi Arabia", id: "sa", flag: "🇸🇦" },
  { country: "Serbia", id: "rs", flag: "🇷🇸" },
  { country: "Singapore", id: "sg", flag: "🇸🇬" },
  { country: "Slovakia", id: "sk", flag: "🇸🇰" },
  { country: "Slovenia", id: "si", flag: "🇸🇮" },
  { country: "South Africa", id: "za", flag: "🇿🇦" },
  { country: "South Korea", id: "kr", flag: "🇰🇷" },
  { country: "Sweden", id: "se", flag: "🇸🇪" },
  { country: "Switzerland", id: "ch", flag: "🇨🇭" },
  { country: "Taiwan", id: "tw", flag: "🇹🇼" },
  { country: "Thailand", id: "th", flag: "🇹🇭" },
  { country: "Turkey", id: "tr", flag: "🇹🇷" },
  { country: "UAE", id: "ae", flag: "🇦🇪" },
  { country: "Ukraine", id: "ua", flag: "🇺🇦" },
  { country: "United Kingdom", id: "gb", flag: "🇬🇧" },
  { country: "United States", id: "us", flag: "🇺🇸" },
  { country: "Venezuela", id: "ve", flag: "🇻🇪" },
];

export default countryList;
